### ISSUE TITLE
CharacterContactListener: add OnContactPersisted and OnContactRemoved

### ISSUE THREAD

**Issue by eliasdaler** [jrouwe/JoltPhysics#1027]
It would be nice for `CharacterContactListener` to be more similar to `ContactListener` and have `OnContactPersisted` and `OnContactRemoved` (so that you can send events when the character exists the sensor, for example).

**Comment by eliasdaler** [comment]
And while we're at it, the docs for `CharacterContactListener::OnContactAdded` say:

> Called whenever the character collides with a body. Returns true if the contact can push the character. 

Which seems outdated since the method doesn't return anything.

**Comment by jrouwe** [comment]
The comment was wrong indeed, I fixed that.

The CharacterVirtual doesn't keep track of previous contacts in the same way as the normal simulation does, so it would require a bit of rework to support this especially since there are many function calls you can do on the character (`Update`, `ExtendedUpate`, `WalkStairs`) that modify it's collision state and to the library it is not obvious when the user is 'done' moving the character.

As a user of the library it shouldn't be hard to track this though. You can store the existing contacts through `GetActiveContacts` before you start modifying the state of the character and then in the `OnContactAdded` callback you can check if it is a new contact / after you finish modifying the character you can compare the old state with the new state to generate contact removed events.

**Comment by eliasdaler** [comment]
> As a user of the library it shouldn't be hard to track this though. You can store the existing contacts through GetActiveContacts before you start modifying the state of the character and then in the OnContactAdded callback you can check if it is a new contact / after you finish modifying the character you can compare the old state with the new state to generate contact removed events.

I see, thanks! If it's hard to implement, then it's probably not worth it. 

I just found `OnContactRemoved` pretty handy for regular bodies, since I didn't need to do the manual tracking. But I guess I can track previous contacts myself as you've explained. :)

**Comment by bryanedds** [comment]
I'd like to explore the addition of these feature. If the user can avoid this sort of manual bookkeeping (and the bugs that come with it), it might be better to OnContactAdded a built-in feature for jolt character contact listeners.

**Comment by jrouwe** [comment]
@eliasdaler The OnContactPersisted/Removed callbacks have been implemented now.
