### ISSUE TITLE
Crash in SkeletonMapperTest sample

### ISSUE THREAD

**Issue by KyleN97** [jrouwe/JoltPhysics#1045]
I'm trying to see how constrains could be used within a mapped skeleton, however when trying to override the constraint type within RagdollLoader::sLoad() it causes a crash straight away.

 Within the void SkeletonMapperTest::Initialize() function i changed:
 
```
 // Load ragdoll
mRagdollSettings = RagdollLoader::sLoad("Assets/Human.tof", EMotionType::Dynamic);	
```
to 
```
// Load ragdoll
mRagdollSettings = RagdollLoader::sLoad("Assets/Human.tof", EMotionType::Dynamic, EConstraintOverride::TypeFixed);
```

Then loading into the test it will crash, the cause seems to be somewhere relevant to 
`mRagdoll->DriveToPoseUsingMotors(mRagdollPose);`

**Comment by jrouwe** [comment]
The DriveToPoseUsingMotors function currently assumes that your ragdoll consists only of SwingTwistConstraint's. It does a hard cast to this constraint type, but since your constraint is a FixedConstraint that will crash. FixedConstraints don't have motors (they're not supposed to move), so this cannot work.

**Comment by jrouwe** [comment]
I changed the crash into an assert in #1047

**Comment by KyleN97** [comment]
Thanks for the clarification!
