### ISSUE TITLE
Annoying identical color

### ISSUE THREAD

**Issue by Snouf-ID** [jrouwe/JoltPhysics#1097]
Hello :)

When I use DrawBodies functions for visual debug, my first dynamic object is the same color as the ground (static object).
Kind of gray/white.
After adding a second dynamic ball, which is indeed a different bright color, I conclude that it's just bad luck for this first color.
This happens starting from the HelloWorld.cpp sample with the ground and the ball.

```c++
BodyManager::DrawSettings settings;   
settings.mDrawShapeColor = BodyManager::EShapeColor::MotionTypeColor;   
m_physics_system.DrawBodies(settings, &m_debug_renderer);   
```

I would expect to never have this color for dynamic, or at least not start with it.
It's confusing in MotionTypeColor mode.

I'm using Jolt 5.0.

thanks in advance

**Comment by jrouwe** [comment]
The coloring rules for MotionTypeColor are very simple:

https://github.com/jrouwe/JoltPhysics/blob/4a08d8d4e1ce7e87fdb16b0708a54a15f9a5379e/Jolt/Physics/Body/BodyManager.cpp#L929-L943

The only reason why a body would be gray is if it is static. All sGetDistinctColor's differ from gray:

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/f90449c4-2f82-46a9-b8eb-b3b269533ace)

(note the first and last ball have the same color because sGetDistinctColor repeats after 36 colors)

So I don't understand how a dynamic object could be gray and it is also not something I see happening in the samples app.

**Comment by Snouf-ID** [comment]
an random drive bug, color is ok in code, sorry
