### ISSUE TITLE
Request for official vcpkg support

### ISSUE THREAD

**Issue by miss-programgamer** [jrouwe/JoltPhysics#1176]
There is currently a vcpkg port of Jolt available, though it is an unofficial one supported by a third party. Would you consider making an official vcpkg port and maintaining it in the future? It would be nice since vcpkg is by far the most convenient way to download C++ dependencies. Thank you for your consideration!

**Comment by jrouwe** [comment]
I'm not very familiar with setting up / using vcpkg so I'm quite happy for someone else to take care of this. Is there any disadvantage of the current package?

**Comment by miss-programgamer** [comment]
Only minor things, like the fact that its name contains "unofficial", which is a bit of a mouthful, but having it maintained in a first party fashion would also means that the library version on vcpkg would pretty much always be up to date with the latest distribution. Of course, I understand that it's a time/effort commitment, so the decision to not go ahead with this is entirely fair.

**Comment by jrouwe** [comment]
@RT2Code, I'm fine if you want to remove the 'unofficial' bit from the vcpkg port. 

I'm planning to release a new version of Jolt soon and I see that you have some [patches](https://github.com/microsoft/vcpkg/blob/master/ports/joltphysics/fix-export.diff) which could perhaps be merged into the main line.

I'm hoping that this change:

https://github.com/microsoft/vcpkg/blob/fe1cde61e971d53c9687cf9a46308f8f55da19fa/ports/joltphysics/fix-export.diff#L9-L12

is no longer needed since you can use `OVERRIDE_CXX_FLAGS` on MSVC too now.

This change:

https://github.com/microsoft/vcpkg/blob/fe1cde61e971d53c9687cf9a46308f8f55da19fa/ports/joltphysics/fix-export.diff#L33-L43

can perhaps be replaced by this change in Jolt:

https://github.com/jrouwe/JoltPhysics/blob/d2cd9e8fe5b9bd662d421d7d2ba60e027d438cd4/Build/CMakeLists.txt#L266-L273

but I'm not very familiar with 'installing' using cmake so I may be completely wrong.

**Comment by RT2Code** [comment]
The unofficial prefix here is misleading. The port is not unofficial at all, only the CMake export is, and [the prefix is used to avoid conflict when upstreams add an official one.](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#add-cmake-exports-in-an-unofficial--namespace).

Now that joltphysics has a built-in CMake export, this patch is essentially obsolete, and I think we can remove it entirely. I'm going to update the vcpkg port.

**Comment by jrouwe** [comment]
Let me know if you need to create another patch. If there is, let's see what I need to change so that you don't need to patch.

**Comment by RT2Code** [comment]
I made a PR to remove the patch and update the port to the 5.1.0 release: https://github.com/microsoft/vcpkg/pull/40526

I'm waiting for the vcpkg team feedback, but it should be good to go. :)

**Comment by jrouwe** [comment]
Thanks for maintaining this!

**Comment by RT2Code** [comment]
And thanks for your hard work on this amazing library. [The PR was merged](https://github.com/microsoft/vcpkg/pull/40526), this issue can be closed.
