### ISSUE TITLE
Core.h defines JPH_USE_NEON

### ISSUE THREAD

**Issue by stephengold** [jrouwe/JoltPhysics#1194]
When I compile with g++ version 10 for 64-bit ARM Linux (aarch64), I get numerous errors and warnings:

```console
In file included from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Jolt.h:9,

                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp:5:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl: In member function ‘JPH::UVec4 JPH::UVec4::Swizzle() const’:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Core/ARMNeon.h:85:77: error: there are no arguments to ‘__builtin_shufflevector’ that depend on a template parameter, so a declaration of ‘__builtin_shufflevector’ must be available [-fpermissive]
   85 |  #define JPH_NEON_SHUFFLE_F32x4(vec1, vec2, index1, index2, index3, index4) __builtin_shufflevector(vec1, vec2, index1, index2, index3, index4)
      |                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:39:9: note: in expansion of macro ‘JPH_NEON_SHUFFLE_F32x4’
   39 |  return JPH_NEON_SHUFFLE_F32x4(mValue, mValue, SwizzleX, SwizzleY, SwizzleZ, SwizzleW);
      |         ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Core/ARMNeon.h:85:77: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
   85 |  #define JPH_NEON_SHUFFLE_F32x4(vec1, vec2, index1, index2, index3, index4) __builtin_shufflevector(vec1, vec2, index1, index2, index3, index4)
      |                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:39:9: note: in expansion of macro ‘JPH_NEON_SHUFFLE_F32x4’
   39 |  return JPH_NEON_SHUFFLE_F32x4(mValue, mValue, SwizzleX, SwizzleY, SwizzleZ, SwizzleW);
      |         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.h:220,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec3.inl:6,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec3.h:295,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec4.inl:6,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec4.h:283,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Jolt.h:14,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp:5:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl: In static member function ‘static JPH::UVec4 JPH::UVec4::sSelect(UVec4Arg, UVec4Arg, UVec4Arg)’:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:157:51: note: use ‘-flax-vector-conversions’ to permit conversions between vectors with differing element types or numbers of subparts
  157 |  return vbslq_u32(vshrq_n_s32(inControl.mValue, 31), inV2.mValue, inV1.mValue);
      |                                                   ^
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:157:41: error: cannot convert ‘const Type’ {aka ‘const uint32x4_t’} to ‘int32x4_t’
  157 |  return vbslq_u32(vshrq_n_s32(inControl.mValue, 31), inV2.mValue, inV1.mValue);
      |                               ~~~~~~~~~~^~~~~~
      |                                         |
      |                                         const Type {aka const uint32x4_t}
In file included from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Core/Core.h:416,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Jolt.h:8,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp:5:
/usr/lib/gcc-cross/aarch64-linux-gnu/10/include/arm_neon.h:27150:24: note:   initializing argument 1 of ‘int32x4_t vshrq_n_s32(int32x4_t, int)’
27150 | vshrq_n_s32 (int32x4_t __a, const int __b)
      |              ~~~~~~~~~~^~~
```
and so on. The complete job log is at https://github.com/stephengold/jolt-jni/actions/runs/10230881139/job/28306198349 .

I don't completely understand what the code is trying to do or why it's failing.

The crux appears to be that Core.h assumes every 64-bit ARM supports NEON:
https://github.com/jrouwe/JoltPhysics/blob/d2cd9e8fe5b9bd662d421d7d2ba60e027d438cd4/Jolt/Core/Core.h#L170-L175

It seems to me `JPH_USE_NEON` should only be defined in the makefile, not in a header file.

Later, in FPControlWord.h, `JPH_USE_NEON` is treated as a synonym for 64-bit ARM:
https://github.com/jrouwe/JoltPhysics/blob/d2cd9e8fe5b9bd662d421d7d2ba60e027d438cd4/Jolt/Core/FPControlWord.h#L67-L72

I have a proposed fix, which I'll submit ASAP.

**Comment by jrouwe** [comment]
I fixed the second error (and more) in #1197:

```
In file included from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.h:220,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec3.inl:6,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec3.h:295,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec4.inl:6,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/Vec4.h:283,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Jolt.h:14,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp:5:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl: In static member function ‘static JPH::UVec4 JPH::UVec4::sSelect(UVec4Arg, UVec4Arg, UVec4Arg)’:
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:157:51: note: use ‘-flax-vector-conversions’ to permit conversions between vectors with differing element types or numbers of subparts
  157 |  return vbslq_u32(vshrq_n_s32(inControl.mValue, 31), inV2.mValue, inV1.mValue);
      |                                                   ^
/home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Math/UVec4.inl:157:41: error: cannot convert ‘const Type’ {aka ‘const uint32x4_t’} to ‘int32x4_t’
  157 |  return vbslq_u32(vshrq_n_s32(inControl.mValue, 31), inV2.mValue, inV1.mValue);
      |                               ~~~~~~~~~~^~~~~~
      |                                         |
      |                                         const Type {aka const uint32x4_t}
In file included from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Core/Core.h:416,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/Jolt.h:8,
                 from /home/runner/work/jolt-jni/jolt-jni/src/main/native/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp:5:
/usr/lib/gcc-cross/aarch64-linux-gnu/10/include/arm_neon.h:27150:24: note:   initializing argument 1 of ‘int32x4_t vshrq_n_s32(int32x4_t, int)’
27150 | vshrq_n_s32 (int32x4_t __a, const int __b)
      |              ~~~~~~~~~~^~~
```

but in order to fix the first error you will need to update to GCC 12. GCC 10 and 11 didn't have the `__builtin_shufflevector` function yet so will not be able to compile. Example [GCC 10](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Carm_neon.h%3E%0A%0Aint32x4_t+function(int32x4_t+v1)%0A%7B%0A++++return+__builtin_shufflevector(v1,+v1,+1,+2,+0,+0)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:37.184204071621295,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1050,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O3',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+GCC+10.5.0+(Editor+%231)',t:'0')),k:29.482462595045376,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+ARM+GCC+10.5.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) vs same example with [GCC 12](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Carm_neon.h%3E%0A%0Aint32x4_t+function(int32x4_t+v1)%0A%7B%0A++++return+__builtin_shufflevector(v1,+v1,+1,+2,+0,+0)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:37.184204071621295,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:arm1210,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O3',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+GCC+12.1.0+(Editor+%231)',t:'0')),k:29.482462595045376,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+ARM+GCC+12.1.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

Is this possbile for you?

**Comment by stephengold** [comment]
Thanks for your efforts and insights.

I can use GCC 12, though there is some downside: the compiled code would require libstdc++.so version 3.4.30 or higher, which might prevent it running on older Linux distros. If portability is a priority, would I be better off building with Clang instead of GCC?

**Comment by jrouwe** [comment]
Actually I realized that there is quite a simple way to support GCC 10+, so I've made that change.

As for using Clang: I'm mostly testing on MSVC and Clang so you may find more issues using GCC, but it should work nonetheless.
