### ISSUE TITLE
No Plane shape

### ISSUE THREAD

**Issue by sherief** [jrouwe/JoltPhysics#126]
Bullet3 and IIRC ODE have a plane collision shape, which is useful in a few cases. Are there any plans to add a similar shape to Jolt? If not, would such a submission be accepted into mainline?

**Comment by jrouwe** [comment]
Hello,

I have never considered supporting a plane shape. It may seem like a very lightweight collision shape, but it has issues and I'm not sure what problem the shape solves. If you'd want to support it in Jolt you would need to create a new Shape that inherits from Shape (not ConvexShape) and then implement all the collision queries. Then there would be a number of 'problem' functions:

- GetLocalBounds/GetWorldSpaceBounds: Because a plane has an infinite size, it will require a VERY large bounding box (bullet uses 10^18). In practice this means that you'll get a very bad broad phase since it has this one giant bounding box in it. Any calculations with it will result in floating point issues.
- GetTrianglesStart/Next: You'd have to decide how to triangulate your infinite plane. If you pick very large triangles, you'll have floating point roundoff issues when you start working with the triangles. If you pick small ones, you need a lot (you don't have any idea which triangles the caller is going to be interested in).
- CastShape/CollideShape: When you find a hit, you'll need to provide mShape2Face. Again because of it's infinite nature, you can't really provide something sensible. In this case you can probably project mShape1Face onto the plane and return it and the simulation will be fine.

All in all, I would recommend just using one or more box shapes to cover the area you need to cover (each box should not be too large to avoid float issues).

**Comment by sherief** [comment]
That is very informative, thanks! I checked the Shape interface and it looks pretty simple, however you've convinced me not to include a plane shape in the first place :D

Thanks again!

**Comment by jrouwe** [comment]
FYI, as of ff50a7a800111b16aa5fcf8a8ab21beda66d64ca there is a PlaneShape now.

> GetLocalBounds/GetWorldSpaceBounds: Because a plane has an infinite size, it will require a VERY large bounding box

This was solved by adding a `size` to the constructor which lets you choose how big you want the bounding box to be (leading to simulation artifacts if you go near the border). If you pick a really big size, you may mess up the broadphase (or at least it could become a really bad BVH).

> GetTrianglesStart/Next: You'd have to decide how to triangulate your infinite plane

The same `size` parameter is used here.

> CastShape/CollideShape: When you find a hit, you'll need to provide mShape2Face

For this function I opted to return a quad that is bigger than the bounding box of the other shape. This prevents numerical precision issues in the solver, but it does mean that the shape returns a different face depending on where you hit it.
