### ISSUE TITLE
Job / Barrier interface access and compile time efficiencies

### ISSUE THREAD

**Issue by sherief** [jrouwe/JoltPhysics#135]
I'm in the middle of implementing a job system for a custom platform, and I noticed that barriers and jobs are restrictively access controlled - for example, Barrier::OnJobFinished() implementations fail to compile unless the barrier implementation is declared inside the class implementing the job system interface, since `Job` is protected. This means I cannot expose a custom job system by merely declaring a class implementing JobSystem in a public header and hide the implementation of my Barrier implementation from the user.

I understand the convenience, but is this level of access control necessary? Job is like a COM interface, I'd prefer looser access controls that allow me to experiment with job system barrier implementations with the implementation static / in an anonymous namespace inside a single compilation unit. 

Would you accept a PR moving Job outside of JobSystem so barrier implementations can be opaque?

**Comment by jrouwe** [comment]
Hello,

I don't want to move the Job class outside of the JobSystem because its interface is not supposed to be called by client code. Clients should only be able to talk to JobHandles and the interface to the JobSystem. If we were to move the Job outside of JobSystem then through JobHandle::GetPtr the Job interface could be gotten and AddDependency/AddRef etc. could be called which is not intended.
