### ISSUE TITLE
Implement an un-damped length constraint

### ISSUE THREAD

**Issue by Joshua-Ashton** [jrouwe/JoltPhysics#159]
Maybe I am misunderstanding the comment here, but what I want is to be able to really pull on it with a lot and it never exceed the maximum length of the rope (like the Point constraints but with a minLength.)

**Comment by Joshua-Ashton** [comment]
Looks like this problem was made a lot worse by what I encountered with https://github.com/jrouwe/JoltPhysics/issues/150#issuecomment-1126067661

There is still some tiny amount of give compared to ballsockets it seems, but a lot more negligable. Would still be nice to not have it potentially thoigh,

**Comment by jrouwe** [comment]
I'm guessing this is about the comment in DistanceConstraint.h?

'''
/// Note that due to the way the damping is implemented, it is impossible to get an undamped oscillation. See comment in AxisConstraintPart::CalculateConstraintProperties.
'''

What it basically means is that if you set frequency and damping to 0 there should not be any oscillation and the constraint will be as stiff as possible. But due to the way the whole simulation is integrated (with an implicit Euler integrator), in practice you will always have damping and some softness. If you don't then the simulation tends to explode. 

My guess is that the point constraints (ball and socket) are stiffer because they remove 3 degrees of freedom and distance constraints only 1. If you want to make a fixed length rope out of sticks I would use the point constraint.

**Comment by Joshua-Ashton** [comment]
I guess if it makes the constraints explode that makes sense. I have had constraints explode with Jolt sometimes, but I am not sure how to make an easy repro case or if this can be fixed easily.

**Comment by jrouwe** [comment]
It usually means that the forces that are pulling on the constraints are too big for the time step you take / the amount of iterations you have specified or objects with very different masses are connected. It's possible that there's a bug somewhere of course, but without a repro case it's hard to say.

**Comment by jrouwe** [comment]
Documentatoin added. If you have an exploding simulation repro, please create a new ticket.
