### ISSUE TITLE
PhysicsSystem::Update crashes when inCollisionSteps > 4

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#171]
That's because PhysicsUpdateContext::Steps is an array with a fixed capacity.

I have specifically written my update loop such that it only calls Update once and rather uses multiple collision steps, to reduce unnecessary internal overhead, but apparently there is an undocumented limit here.

I would prefer, if there was no such limit.

**Comment by jrouwe** [comment]
Should be fixed with #173. Note that the job system will require extra jobs (the job graph is built in the beginning) and the barrier will also need to be able to hold extra jobs. If you're using the example implementation JobSystemThreadPool you'll eventually run out of the fixed size array of jobs in the job barrier.
