### ISSUE TITLE
Question about support for performance settings (semi- vphysics-jolt related)

### ISSUE THREAD

**Issue by Bagellll** [jrouwe/JoltPhysics#228]
Hey there,

Allow me to preface my question a little. There was [an issue](https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/93) posted on the [VPhysics-Jolt](https://github.com/Joshua-Ashton/VPhysics-Jolt) repo about the interface not returning real values from the performance settings struct, which looks like this from the source-sdk:
```cpp
// Don't ever change these values, or face all kinds of subtle gameplay changes
const float k_flMaxVelocity = 2000.0f;
const float k_flMaxAngularVelocity = 360.0f * 10.0f;

const float DEFAULT_MIN_FRICTION_MASS = 10.0f;
const float DEFAULT_MAX_FRICTION_MASS = 2500.0f;
struct physics_performanceparams_t
{
	int	maxCollisionsPerObjectPerTimestep;	// object will be frozen after this many collisions (visual hitching vs. CPU cost)
	int	maxCollisionChecksPerTimestep;		// objects may penetrate after this many collision checks (can be extended in AdditionalCollisionChecksThisTick)
	float	maxVelocity;				// limit world space linear velocity to this (in / s)
	float	maxAngularVelocity;			// limit world space angular velocity to this (degrees / s)
	float	lookAheadTimeObjectsVsWorld;		// predict collisions this far (seconds) into the future
	float	lookAheadTimeObjectsVsObject;		// predict collisions this far (seconds) into the future
	float	minFrictionMass;			// min mass for friction solves (constrains dynamic range of mass to improve stability)
	float	maxFrictionMass;			// mas mass for friction solves

	void Defaults()
	{
		maxCollisionsPerObjectPerTimestep = 6;
		maxCollisionChecksPerTimestep = 250;
		maxVelocity = k_flMaxVelocity;
		maxAngularVelocity = k_flMaxAngularVelocity;
		lookAheadTimeObjectsVsWorld = 1.0f;
		lookAheadTimeObjectsVsObject = 0.5f;
		minFrictionMass = DEFAULT_MIN_FRICTION_MASS;
		maxFrictionMass = DEFAULT_MAX_FRICTION_MASS;
	}
};
```

In the actual issue it could be patched by just storing the struct without doing anything but that's what leads me to my question.

Is it possible to introduce these settings into Jolt?

Are similar settings already implemented that can be changed during runtime?

I understand that it won't be 1:1 with the source engine implementation but that's about it, the question itself isn't dependent on the 'volt' repo but I thought I should still mention it.

Also, I apologize if I'm asking an easy question, my knowledge of Jolt is pretty limited right now. Thanks in advance for reading.

**Comment by jrouwe** [comment]
Hello:

maxVelocity / maxAngularVelocity: These are implemented per Body in Jolt, see: BodyCreationSettings::mMaxLinearVelocity/mMaxAngularVelocity (note angular velocity in radians instead of degrees). They can be adjusted at runtime by calling Body::GetMotionProperties()->SetMaxLinearVelocity/SetMaxAngularVelocity. 

maxCollisionsPerObjectPerTimestep / maxCollisionChecksPerTimestep / lookAheadTimeObjectsVsWorld / lookAheadTimeObjectsVsObject: These don't make any sense for Jolt. The system just works in a different way.

minFrictionMass / maxFrictionMass: I can't find any documentation on what this does, so I can't really answer the question for these two. 

Regards,

Jorrit.

**Comment by Bagellll** [comment]
Thanks a ton. I'll play around with it and experiment
