### ISSUE TITLE
VehicleConstraint wheel collider problem

### ISSUE THREAD

**Issue by attilaz** [jrouwe/JoltPhysics#241]
Thanks for sharing this great physics engine.

We are testing VehicleConstraint sample app and found an issue when a wheel rolls over a small dynamic object, like for example the convex hull shooted object. The wheel behaves different from what is expected. This happens in both the ray and sphere wheel collision mode.  Please look at attached video:

https://user-images.githubusercontent.com/4198194/192794942-aa3795ae-4e9e-4d87-ae44-86fccae7ff0b.mp4

**Comment by jrouwe** [comment]
Hello,

I see two things and I'm not sure which thing you mean.

1. The wheel jumps up quite unnaturally. This happens because with the VehicleConstraint model the wheel is not a rigid body, so it doesn't really have inertia. This could be solved by playing around with the suspension frequency and damping or adding a bit of smoothing on the game rendering side.

2. The car body dips down whenever the car drives over a convex shape. This is a known issue and is an artifact of the iterative solver that Jolt is using. Basically if a light object is sandwiched between two heavy objects (the static floor and the car body), the light object is not able to transfer enough force from the ground to the car body to keep the car body up. You can see this effect in the HeavyOnLightTest sample, the boxes on the right have a lot of penetration because they're on top of light objects:

![image](https://user-images.githubusercontent.com/1621693/192872667-0e5e32fe-e39c-4b02-bbb3-94b47fd0269b.png)

There are a couple of ways to improve this:

1. You can increase the number of velocity steps (global settings PhysicsSettings::mNumVelocitySteps or if you only want to increase it on the vehicle you can use VehicleConstraintSettings::mNumVelocityStepsOverride). E.g. going from 10 to 30 steps in the HeavyOnLightTest sample makes the penetration a lot less:

![image](https://user-images.githubusercontent.com/1621693/192873233-58e08fdf-52eb-4ce1-8199-bf288f8bda2e.png)

This solution costs CPU cycles. The number of position steps can also be increased (the first prevents the body from going down, the second corrects it if the problem did occur which inevitably happens due to numerical drift).

2. You can reduce the mass difference between the vehicle body and the rubble on the floor (by making the rubble heavier or the car lighter). This also decreases the error.

3. You could filter out collisions between the vehicle ray cast and the rubble completely. This would make the wheels ignore the rubble but would cause the vehicle to drive through it as if nothing happened. You could create fake wheels (keyframed bodies) that move along with the vehicle and that only collide with rubble (and not the vehicle or the ground). This would cause the vehicle to push away the rubble without the rubble being able to affect the vehicle (unless it hits the main body of course).

4. (this requires some work on my side) We could give artificially increase the weight that the wheel contacts see to pretend that they are driving over a heavy body instead of a light one (this means the vehicle will have more difficulty pushing the object away, which may cause visual artifacts too). The advantage of this is that you only affect the mass of the rubble for the purpose of vehicle vs rubble collision, all other interactions remain 'normal'.

**Comment by attilaz** [comment]
Thanks for the quick answer.

Our main problem is the "car body dips down". We will try the solutions you proposed. We are developing for mobile so CPU is a very scarce resource. 

We tried to increase the global velocity steps but we didn't see any difference. 

We have also tried to increase the density of the rubble. With 100x increase the behavior was better but not "correct". With 1000x increase the simulation looked ok.  Overriding mass of rubble to 1500 (the car mass) didn't help. Overriding to 10000 looked ok.  

Another test with light boxes ( BoxShape(Vec3(0.5f, 0.15f, 0.5f)), density 1000 ).
The box rotation direction looks strange. 

https://user-images.githubusercontent.com/4198194/192965411-b5c557ff-ab18-468c-89b7-440974afd7c2.mp4

**Comment by jrouwe** [comment]
I think you modified the sample code, right? Can you attach it here so I can take a look? (for both movies if possible)

**Comment by attilaz** [comment]
Here are the modified VehicleTest.cpp/h files.
You can try it with VehicleConstraint Sample with "Flat" test settings.

[VehicleTest.ZIP](https://github.com/jrouwe/JoltPhysics/files/9681504/VehicleTest.ZIP)

**Comment by jrouwe** [comment]
Thanks! The setup is correct. I think I made a sign error somewhere, let me investigate.

**Comment by jrouwe** [comment]
It was a very silly mistake, I fixed it in https://github.com/jrouwe/JoltPhysics/commit/eacf93c66976e4ded29dd724f0ac8e4cc89ce1f0.

The effect is still there (because of the reasons mentioned above) but it is much less noticeable.

**Comment by attilaz** [comment]
Thanks! It is much better now.
