### ISSUE TITLE
Samples mouse input broken on remote desktop

### ISSUE THREAD

**Issue by tksuoran** [jrouwe/JoltPhysics#283]
Mouse is way over sensitive when running Samples over remote desktop (from linux at least).

**Comment by jrouwe** [comment]
Yes I've noticed. I'm using DirectX to read the mouse state and IDirectInputDevice8::GetDeviceState starts returning weird numbers when going through RDP. I should probably rewrite it one day to use one of the more modern ways of reading input.

**Comment by jankrassnigg** [comment]
This is actually a common issue. I had to fix that in the past as well. If you use any "modern" method (e.g. WM_INPUT aka "raw input") you will run into this issue as well.

The only way to get this working right, is to actually use the stock windows messages (WM_MOUSEMOVE), because only they get properly adjusted for remote desktop.

IIRC the way I ended up fixing it was to detect whether the app is running in remote desktop mode, and use WM_MOUSEMOVE rather than WM_INPUT in that case. WM_MOUSEMOVE has the disadvantage that you won't get input anymore once the mouse has reached the window borders, so usually you would work around this by re-centering the mouse all the time, but IIRC that is not allowed in remote desktop, so you end up having to live with the fact that you can't move the mouse endlessly. It's really not designed with gaming in mind, I guess.

**Comment by jrouwe** [comment]
Fixed as per @jankrassnigg's suggestion in #309 (although I used GetCursorPos instead of WM_MOUSEMOVE).
