### ISSUE TITLE
Jolt vs PhysX?

### ISSUE THREAD

**Issue by alienself** [jrouwe/JoltPhysics#323]
Hi there!

Love your physics engine and definitely considering using it for my next project.
What are the known limitations of Jolt compared to PhysX? Did you run benchmarks against PhysX 5.0?
Are you planning to keep supporting it in the future? 
Do you have a roadmap of upcoming features?

Thanks

**Comment by Pierre-Terdiman** [comment]
https://github.com/Pierre-Terdiman/PEEL_PhysX_Edition

**Comment by jrouwe** [comment]
Hello,

PhysX is obviously a much bigger project and it has more features than Jolt. I think the biggest limitation of Jolt right now is that if your simulation requires all physics objects to be on a single pile then it does not scale well (i.e. the entire simulation will run on a single CPU). If your physics objects are spread out more, then it will use all CPU cores and then the performance is pretty decent. This is a fixable limitation, but as this limitation hasn't been an issue for me, I haven't spent time on it.

I haven't tried out PhysX 5.0 yet, but if you want to use the PEEL test above then please keep in mind that the Jolt version in there has none of the more modern CPU instructions enabled, it links against the Release instead of the Distribution version (which means there's some debug code in there) and the number of solver steps are set to default which is good for a high quality simulation, but you can gain quite a bit by lowering that. You can find my performance comparison for PhysX 4 [here](https://jrouwe.nl/jolt/JoltPhysicsMulticoreScaling.pdf) which also includes source code to run the test yourself if you want.

With respect to support: I intend to keep working on this, but as it is my hobby project, I don't really have a roadmap for it. I have a large to do list (which I'd rather not disclose as that will create expectations) and I tend to work on what is requested by the community. I think the current popular request is support for double precision, so that's one of the next things to look at.
