### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by meshula** [jrouwe/JoltPhysics#37]
Just gave it a go, and the performance and simulation robustness is very nice on my machine, compared to, for example my own physics engine ;) The only particular anomaly I spotted was in the big-heavy-cubes test, there seems to be a bit of interpenetration between the pairs of stacked cubes that doesn't quite resolve after a few seconds. I was impressed overall with how solid the constraint resolution is in your engine.

I was wondering if there is anything you can say about the history of the project? Is this a from scratch learning exercise, or it is one in a series of engines? I saw your other repo about swept ellipsoids, and imagine that you must have been working in this problem domain for a while already.

**Comment by meshula** [comment]
Ah, I just spotted your homepage link. I have played many of your games :) I modify my question to a statement, and just say, thanks for sharing your work!

**Comment by jrouwe** [comment]
Thank you very much! 

I've been working on Jolt Physics since mid 2014 although it was never the plan to make a physics engine. It actually started its life as a GPU based ray cast vs mesh test. Collision detection has always been my main interest indeed, but once I had all the collision detection routines written, I had to write something to use them :)

The heavy cubes test shows one of the big problems the Sequential Impulse solver has. As it is an iterative solver, we solve the collision between the light cube and the floor and between light / heavy cubes separately. The 50x heavier cube pushes the light cube much more down than the light cube can push the heavy cube back up due to its collision with the ground. You can 'fix' this by giving the algorithm more iterations. Go to  Physics Settings / Num Velocity Steps and set it to 15 you see that there is already much less penetration.

**Comment by meshula** [comment]
Heh, that sounds like a familiar history ;)

Balancing iterations versus simulation accuracy is verrrry familar!

At LucasArts, the engines I worked on converged on this paper pretty much -

https://animation.rwth-aachen.de/media/papers/2006-CASA-ConstraintBasedCollisions.pdf

Reference 14 is particularly interesting because we had Fedkiw working with us in the office, so we worked the shock propagation method in.

[14] Eran Guendelman, Robert Bridson, and Ronald Fedkiw. Nonconvex rigid bodies with stacking. ACM Transactions on Graphics, 22(3):871–878, July 2003.

I had mixed results with it though, due to the structure of the engine architecture, constructing the contact graph wasn't always practical. When it works, it seems like a magic trick, but it made places where we couldn't use it feel a bit,,, rubbery in comparison,,, I guess is how I would describe it. It was fantastic for level layout though, throw a pile of objects on a set, snap your fingers, and everything pops out of inter-penetration.

These guys were also on our team - https://www.uni-weimar.de/~caw/papers/p7-kacic-alesic.pdf - and section 4.2 is a treasure. I used those limits to guide restitution time steps.

In terms of a small world, the author of reference [10] just joined the team I'm on (not working on physics though)!

Sorry for the wall of text, I obviously love this stuff and can't help myself.

**Comment by jrouwe** [comment]
That's a wall of text indeed! Thanks for all the references, I guess I have some reading to do. It's always nice to see what kind of CPU power the film industry can throw at things (we only have 3 ms per frame) :)

**Comment by meshula** [comment]
The papers I linked were used in an ILM LucasArts collab, so it all wound up in The Force Unleashed and other games :)

**Comment by meshula** [comment]
(we publicized our use of Havok, but Havok was a component in a larger physics engine, which didn't get publicized...)
