### ISSUE TITLE
Sensors behave strangely with compound shapes

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#424]
I'm seeing some strange output from `OnContactAdded` and `OnContactRemoved` when dealing with compound shapes.

I modified `SensorTest` (fork [here](https://github.com/jrouwe/JoltPhysics/compare/master...mihe:JoltPhysics:sensor-compound)) to use a fairly basic scene, where three boxes named (through user data) `Bottom`, `Middle` and `Top` make up a compound shape that falls through a static sensor:

https://user-images.githubusercontent.com/4884246/216774249-2acf8acd-4f89-42e4-b4c8-1473454262e0.mp4

If I then log the relevant calls to `OnContactAdded` and `OnContactRemoved` I get something that looks like this:

```
Added shape: Bottom
Body entered sensor
Added shape: Middle
Removed shape: Bottom
Added shape: Top
Removed shape: Middle
Added shape: Bottom
Added shape: Middle
Removed shape: Bottom
Removed shape: Middle
Removed shape: Top
Body exited sensor
```

I would expect to see something more like this:

```
Added shape: Bottom
Body entered sensor
Added shape: Middle
Added shape: Top
Removed shape: Bottom
Removed shape: Middle
Removed shape: Top
Body exited sensor
```

The context/use-case here is that Godot not only signals when bodies enter/exit a sensor, but also when individual shapes of a body enter/exit a sensor, which I'm finding difficult to implement with the way things behave right now.

Is this a bug, or is there maybe some other way I can achieve this?

**Comment by jrouwe** [comment]
This is caused by contact point reduction, if you turn this off in the Physics Settings submenu:

![image](https://user-images.githubusercontent.com/1621693/216779606-45d902db-5e0a-4d97-b1fe-35eb30bf7871.png)

Then it reports what you would expect. What happens is that it finds multiple contacts with the sub shapes that have similar normals and combines them. At that point it has to choose which sub shape to report the contact for and it does that in a deterministic way, but if the contacts change then the sub shape can change as well.

I'll make it possible to turn off contact point reduction on a per body basis.

**Comment by jrouwe** [comment]
> Is there any major downside to having mUseManifoldReduction disabled?

Yes there can be a big performance penalty (basically you can generate many extra contact points, slowing down the solver). 

I've created #426 to be able to turn off manifold reduction per body. I would use this only when needed (i.e. on the sensors).
