### ISSUE TITLE
Removing sub-shapes while in a sensor results in strange contact reports

### ISSUE THREAD

**Issue by mihe** [jrouwe/JoltPhysics#430]
I'm getting some more interesting output from `OnContactAdded` and `OnContactRemoved` when dealing with compound shapes.

I'll preface by saying that I don't really understand how `SubShapeID` works, and no amount of staring at it seems to fix that, so it could just be that I'm fundamentally misusing them, through `SubShapeIDPair`, but I'm curious to hear your thoughts on it.

To illustrate my problem, I've added a new test to `Samples` (fork [here](https://github.com/mihe/JoltPhysics/blob/sensor-sub-shapes/Samples/Tests/General/SensorSubShapeTest.cpp)) that much like the one in #424 has a compound shape of three boxes pass through a static sensor, named `Left`, `Middle` and `Right`.

This time I'm also removing one of the shapes every time the body reaches the center of the sensor. I do this by rebuilding the entire `StaticCompoundShape` from scratch, which I'm sure isn't ideal, but that is none the less what I'm doing.

Here's what that looks like:

https://user-images.githubusercontent.com/4884246/217529623-55b50694-87c0-4915-b962-5e9c69aa8356.mp4

Here's what a heavily cleaned up version of the output looks like from the first two passes through the sensor:

```
Starting...

Body entering sensor
  OnContactAdded: [Sensor, Right]
  OnContactAdded: [Sensor, Middle]
  OnContactAdded: [Sensor, Left]

Removing the left shape
  OnContactAdded: [Sensor, Right]
  OnContactRemoved: [Sensor, Middle]
  OnContactRemoved: [Sensor, Left]

Body exiting sensor
  OnContactRemoved: [Sensor, Right]
  OnContactRemoved: [Sensor, Right]

Reached the far edge, turning back...

Body entering sensor
  OnContactAdded: [Sensor, Left]
  OnContactAdded: [Sensor, Middle]
  OnContactAdded: [Sensor, Right]

Removing the middle shape
  OnContactAdded: [Sensor, Right]
  OnContactRemoved: [Sensor, Middle]
  OnContactRemoved: [Sensor, Left]

Body exiting sensor
  OnContactRemoved: [Sensor, Right]
  OnContactRemoved: [Sensor, Right]

Reached the starting point.
```

As you might be able to see, the removal of the `Left` shape triggers some peculiar contact reports, where a new `Right` shape gets added and the old `Left` and `Middle` are removed. This results in the remaining overlapping shapes being the old `Right` and new `Right`. I assume this is because the new sub-shapes end up with IDs identical to the old ones, but shifted?

I guess the ideal output would be that it only reported the removed shape as having been removed, and then correctly report the two remaining shapes when they exit the sensor. So the first pass through the sensor would then look something like this:

```
Starting...

Body entering sensor
  OnContactAdded: [Sensor, Right]
  OnContactAdded: [Sensor, Middle]
  OnContactAdded: [Sensor, Left]

Removing the left shape
  OnContactRemoved: [Sensor, Left]

Body exiting sensor
  OnContactRemoved: [Sensor, Right]
  OnContactRemoved: [Sensor, Middle]

Reached the far edge, turning back...
```

I assume something like that would require `SubShapeID` to be stable across the two compound shapes though, and obviously there's no connection between the old and new shapes besides having identical user data, so I would frankly be happy if it simply reported all shapes as having been removed, only to immediately re-add the remaining shapes. So the first pass through the sensor would then look something like this:

```
Starting...

Body entering sensor
  OnContactAdded: [Sensor, Right]
  OnContactAdded: [Sensor, Middle]
  OnContactAdded: [Sensor, Left]

Removing the left shape
  OnContactRemoved: [Sensor, Right]
  OnContactRemoved: [Sensor, Middle]
  OnContactRemoved: [Sensor, Left]
  OnContactAdded: [Sensor, Middle]
  OnContactAdded: [Sensor, Right]

Body exiting sensor
  OnContactRemoved: [Sensor, Right]
  OnContactRemoved: [Sensor, Middle]

Reached the far edge, turning back...
```

**Comment by jrouwe** [comment]
I'm going to have to investigate this a bit more later (don't have much time right now).

Sub shape IDs are basically the concatenated bits from parent to child shape. So if you have CompoundShapeA containing CompoundShapeB containing MeshShapeC then the sub shape ID of a triangle in the mesh may be CCCCCCCBBAAA. The number of sub shapes in a compound is fixed, so it knows how many bits it needs, so shape A knows that it needs to take 3 bits. B has less shapes so only need 2 bits and a mesh shape has needs 7 bits to encode its triangle index.

This means that if you change the shape and you reuse an old sub shape ID that the bits don't make sense anymore (maybe you only need 2 bits for A now). I never ran into this issue because we don't change shapes on the fly for dynamic objects (we create new bodies if this happens). I need to think about this a bit more as by the time the system sends the callbacks, the old shapes are long gone, so there's no way you can get a ContactRemoved callback that makes sense at that point.

**Comment by jrouwe** [comment]
I have thought about this some more and I think it's possible to properly support sending shape indices to Godot.

**Option 1:**
The OnContactAdded/Persisted/Removed pass in the user data of the shapes that are colliding. This introduces additional overhead since the user datas need to be fetched and more importantly they will need to be stored in the contact cache which will bloat the data structures. The data needs to be stored because at the time of the contact callbacks, the old shape is gone. Not a big fan of this option.

**Option 2:**
Supporting it in the Godot plugin. In JoltCollisionObject3D you'd add a ```Ref<Shape> previous_shape```. Whenever the shape changes, and previous_shape == nullptr you'd fetch the old shape of the body and store it here (purpose is to keep the shape that was used during the last simulation step). At the end of every physics simulation step you'd set previous_shape = nullptr to release the previous shape and free the memory.

In the ContactListener you treat the callbacks slightly different than before:

* OnContactAdded - this can just stay as is, you can use the sub shape IDs to resolve the shape index
* OnContactRemoved - if previous_shape != nullptr you'd use previous_shape to convert the sub shape ID to a shape index
* OnContactPersisted - if previous_shape != nullptr you'd first need to get the user data using the sub shape id on the old shape and then do the same on the new shape. If they're different then the same sub shape ID maps to different shapes so internally you would need to trigger a contact remove of the old sub shape and then contact add of the new sub shape. 

This was quite difficult to describe, so I'm hoping that you understand the idea. What do you think?
