### ISSUE TITLE
CharacterVirtual collides with Sensors

### ISSUE THREAD

**Issue by 0xc0de** [jrouwe/JoltPhysics#448]
It seems that CharacterVirtual is not sensitive to sensors. If I add a sensor to the scene, CharacterVirtual collides with it like a normal rigid body. Is this the normal behavior of CharacterVirtual and is there a workaround?

**Comment by jrouwe** [comment]
It's a bug that CharacterVirtual collides with sensors, I'll fix that (see #449). What I would recommend is to pair a CharacterVirtual with a Character inside (see [this](https://github.com/jrouwe/JoltPhysics/blob/1e760859308c2b6c4f4951c40e6d80b7132aea28/Jolt/Physics/Character/CharacterVirtual.h#L92) comment) so that it can be detected by sensors, can be found with collision queries and can interact with fast moving physics objects.

**Comment by jrouwe** [comment]
#449 has been merged.
