### ISSUE TITLE
CastRay questions

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#46]
Hi, I'm currently testing integrating Jolt into [our engine](https://github.com/ezEngine/ezEngine) as a replacement for PhysX and have to say I'm extremely impressed. Awesome job!

So as I go along, I guess I'll create a bunch of tickets for questions and feedback.

In NarrowPhaseQuery there are two CastRay functions. The documentation isn't fully clear on what the first one does exactly. It says "returns true if it finds a hit closer than ioHit.mFraction". Does this mean it is an "any hit" function? I've tried it, and so far it always returned the closest hit, not just any hit, but maybe that's just because of my limited test case. So if I want the closest hit, which one should I use? Do I need a closest hit collector? And if all I want is to do an "any hit" check, what's the fastest option?

These things could be spelled out a bit more precisely in the code documentation.

Another thing I noticed is that the first CastRay function doesn't take RayCastSettings. Is that an oversight or is there a reason why these options don't make sense here?

Third, the RayCastResult doesn't contain information about the normal at the hit position. I'm a bit surprised by that, the normal can be quite useful (e.g. for bouncing / ricocheting of projectiles, particles and so on). Is there an easy and efficient way to compute the normal myself, that I haven't found yet? If not, would be nice, if the raycast function would return that, or have at least a flag to please compute the normal as well.

**Comment by jrouwe** [comment]
Hello, good to hear you like it! Looking at your engine, I see it supports MacOS while Jolt doesn't at the moment (I think it will compile fine with maybe a few tweaks here and there but I don't own a Mac so I can't check).

The CastRay(const RayCast &inRay, RayCastResult &ioHit, ...) function will always return the closest hit. ioHit.mFraction is only used to limit the search interval. This function is slightly faster than the other CastRay function, but it is less flexible as it will find only 1 hit and it doesn't allow you to specify how to treat convex objects / back facing triangles (so yes it doesn't have RayCastSettings on purpose). 

The hit position is trivial to calculate (inRay.GetPositionOnRay(ioHit.mFraction)) and the normal can be collected by calling Body::GetWorldSpaceSurfaceNormal. I don't collect the normal for every hit as many of the hits will be discarded (because they're not the closest hit) so calculating the normal for all of them would have been a waste.

You're right that the documentation is not clear on all of these points and I've updated it (see #47).

**Comment by jankrassnigg** [comment]
> I see it supports MacOS while Jolt doesn't at the moment

That's no problem. I've copied the code over and put it into our own build system, so no worries there, and otherwise you already build it with Clang, so I would be surprised if there are any major issues on Mac (I also don't own one and our Mac support is just rudimentary, rendering is currently DX11 only).

> the normal can be collected by calling Body::GetWorldSpaceSurfaceNormal

Ah, that's good to know, wasn't aware of that feature yet.

> I've updated it (see https://github.com/jrouwe/JoltPhysics/pull/47).

That was quick, thanks! :)

**Comment by Pierre-Terdiman** [comment]
I can confirm that the second CastRay function is slower than the first one, but it is unfortunately the only one we can use to support "backface culling".

FWIW here's how I retrieve the normal after the function returns, please tell me guys if there is a more efficient way (that lock doesn't look great):

```
static inline void FillResultStruct(const RayCast& raycast, PintRaycastHit& hit, const RayCastResult& result)
{
	const Vec3 outPosition = raycast.mOrigin + result.mFraction * raycast.mDirection;

	hit.mImpact	= outPosition;
	hit.mDistance	= (outPosition - raycast.mOrigin).Length();

	BodyLockRead lock(gPhysicsSystem->GetBodyLockInterface(), result.mBodyID);
	if (lock.Succeeded())
	{
		const Body& hit_body = lock.GetBody();

		const Vec3 normal = hit_body.GetWorldSpaceSurfaceNormal(result.mSubShapeID2, outPosition);
		hit.mNormal	= normal;

		hit.mTouchedActor	= PintActorHandle(&hit_body);
		hit.mTouchedShape = null;
	}
	else
	{
		hit.mNormal.Zero();
		hit.mTouchedActor	= null;
		hit.mTouchedShape	= null;
	}

	hit.mTriangleIndex	= INVALID_ID;
}

```

**Comment by jrouwe** [comment]
In your case you can probably use GetBodyLockInterfaceNoLock instead of GetBodyLockInterface since you won't be modifying objects while querying them. That removes most of the overhead.
