### ISSUE TITLE
Assert triggered in QuadTree::ValidateTree when adding bodies in bulk

### ISSUE THREAD

**Issue by peter1745** [jrouwe/JoltPhysics#470]
I'm having a problem when running the engine I'm working in Debug mode with Jolt, specifically I'm adding 10 bodies to the Jolt scene using `BodyInterface::AddBodiesPrepare` and `BodyInterface::AddBodiesFinalize`.

The problem is that when I call `BodyInterface::AddBodiesPrepare` in Debug mode it asserts in `QuadTree::GetBodyLocation` which is called from `QuadTree::ValidateTree` in Debug mode.

This is the error message: `QuadTree.cpp:113: (mAllocator->Get(outNodeIdx).mChildNodeID[outChildIdx] == inBodyID) Make sure that the body is in the node where it should be`.

![image](https://user-images.githubusercontent.com/7275084/224702933-00a0244b-3d48-4057-897a-87fb77c13217.png)

It's the very first body in the `ioBodies` array that's tripping this assert, the body itself looks fine, it's just a simple dynamic body with a `ConvexHullShape` (the data for that shape was read from a file, but it was created successfully), unsure if it matters but the body ID is `33554495`.
From the looks of things it works just fine in Release mode, so I'm slightly confused as to why it's tripping this assert, any help would be appreciated 🙂

**Comment by jrouwe** [comment]
Hello,

This is a pretty serious assert. It means you have somehow corrupted the broad phase. The reason you're not seeing it in release mode is because those asserts are not present there (ValidateTree is ifdef DEBUG). I would expect the game to crash sooner or later on this, or at least those bodies to not collide with anything. I have never seen this assert trigger before and we're definitively batch adding lots of bodies, so I'm pretty sure that that function works.

* Are you sure that you did not specify the same BodyID multiple times in the same batch?
* Are you sure that the body is not already added?
* Are you adding bodies from multiple threads? And if so are you using the locking version of the BodyInterface?
* Are you doing anything between AddBodiesPrepare and AddBodiesFinalize? (and do you preserve the body ID array between those calls? They are shuffled around and the algorithm relies on them not being touched)

**Comment by peter1745** [comment]
> Hello,
> 
> This is a pretty serious assert. It means you have somehow corrupted the broad phase. The reason you're not seeing it in release mode is because those asserts are not present there (ValidateTree is ifdef DEBUG). I would expect the game to crash sooner or later on this, or at least those bodies to not collide with anything. I have never seen this assert trigger before and we're definitively batch adding lots of bodies, so I'm pretty sure that that function works.
> 
> * Are you sure that you did not specify the same BodyID multiple times in the same batch?
> * Are you sure that the body is not already added?
> * Are you adding bodies from multiple threads? And if so are you using the locking version of the BodyInterface?
> * Are you doing anything between AddBodiesPrepare and AddBodiesFinalize? (and do you preserve the body ID array between those calls? They are shuffled around and the algorithm relies on them not being touched)

Thanks for the quick reply!
I'm certain that there are no duplicate ids in the batch, and the bodies haven't been added prior to this crash.
We're currently only adding bodies from one thread, although we're still using the locking interface since we'll be working with multiple threads later on.
I'm also not doing anything between calling AddBodiesPrepare and AddBodiesFinalize.

But if it's caused by some sort of memory corruption then I'm pretty sure it's not the fault of Jolt, we've had a few memory issues in the engine for a while, so maybe it could be caused by that?

The interesting thing is that after having this assert I continued working on some other parts of the physics engine, and I'm no longer able to reproduce the issue reliably.
I've also been using this system for quite a while and haven't had this issue before today.

I suppose it could be some memory corruption in that case
