### ISSUE TITLE
User data on bodies and shapes

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#48]
Both shapes and bodies have user data, but interestingly on bodies user data is a void* whereas on shapes it is a uint32. Is there a reason for this difference? I would have expected void* on both.

Furthermore, bodies are created with a BodyCreationSettings struct, which does not contain a member for user data. That means (as far as I can tell) that I first have to create the body and then use a BodyLockWrite to get access and set the user data. IMO it would be useful to be able to set the user data through the settings object.

**Comment by jrouwe** [comment]
The original reason for it was that the uint32 fits nicely into the padding so that it didn't make Shape bigger than needed (and I'm not using it). But you're the second to ask, so I will turn it into a uint64 and I will do the same for Body to make it consistent. I'll add it to BodyCreationSettings too.

**Comment by Pierre-Terdiman** [comment]
Yeah. I was the first person to ask :)  Thanks for changing this!
