### ISSUE TITLE
Ability to specify stiffness/damping instead of frequency/damping for springs

### ISSUE THREAD

**Issue by jrouwe** [jrouwe/JoltPhysics#555]
Needed to make the following tasks redundant godot-jolt/godot-jolt#346, godot-jolt/godot-jolt#347, godot-jolt/godot-jolt#348, godot-jolt/godot-jolt#349, godot-jolt/godot-jolt#350.

This will most likely be implemented by creating an enum that allows the user to specify if MotorSettings use frequency/damping or the more traditional stiffness/damping values. Also needed for DistanceConstraint, SliderConstraint and VehicleConstraint.

Work in progress here: https://github.com/jrouwe/JoltPhysics/tree/feature/stiffness_and_damping

FYI @mihe

**Comment by mihe** [comment]
Wonderful! As someone who's a complete caveman when it comes to this stuff I'm surprised the two methods can actually co-exist like this.

I assume there's no way I can take this for a spin right now, considering there's nothing feeding into `CalculateConstraintPropertiesWithStiffnessAndDamping`, right?

**Comment by jrouwe** [comment]
Yes, it is incomplete

**Comment by jrouwe** [comment]
I just submitted a version that should work. It's missing unit tests etc. so I'm not 100% sure if it is correct but I think it should be testable now.

**Comment by mihe** [comment]
Great, I'll give it a try in a little bit and report back.

**Comment by mihe** [comment]
Seems to work, as far as I can tell!

This seems to satisfy the stiffness and damping properties on Godot's 6DOF constraint, which is fantastic, but just so I understand things clearly, this isn't meant to cover things like the softness/relaxation/bias/restitution/ERP properties on some of the other constraints, right?

**Comment by jrouwe** [comment]
Hello,

Going through the constraints:

**HingeJoint3D**

HINGE_JOINT_BIAS  - You can simply ignore this one. In Bullet/Godot if a constraint is violated (e.g. because too much force was applied or because they simply didn't start in the correct configuration) the error is fixed by applying an extra impulse every time step to drive the joint to the correct location again, the bias controls how fast this is done. In Jolt this is done in the ```Constraint::SolvePositionConstraint``` function which uses a global setting ```PhysicsSettings::mBaumgarte``` and works slightly different. 

HINGE_JOINT_LIMIT_SOFTNESS - It appears that this value is not used for anything at all in Godot! It sets m_limitSoftness, but it is never read. It looks like this one can be ignored as well.

HINGE_JOINT_LIMIT_BIAS, HINGE_JOINT_LIMIT_RELAXATION - I have the feeling that there [is a bug in this line](https://github.com/godotengine/godot/blob/543750a1b3f5696f9ba8e91cb49dc7db05d2ae62/servers/physics_3d/joints/godot_hinge_joint_3d.cpp#L295) and it should have been:

```
velrelOrthog *= (real_t(1.) / denom) * relaxation;
```

If that's the case then the values are only used [in this line](https://github.com/godotengine/godot/blob/543750a1b3f5696f9ba8e91cb49dc7db05d2ae62/servers/physics_3d/joints/godot_hinge_joint_3d.cpp#L317):

```
real_t amplitude = ((angVelB - angVelA).dot(axisA) * m_relaxationFactor + m_correction * (real_t(1.) / p_step) * m_biasFactor) * m_limitSign;
```

Which to me looks like the angular spring equation:

```
torque = -k * angle_error - c * relative_angular_velocity
```

where k = m_biasFactor/HINGE_JOINT_LIMIT_BIAS and c = m_relaxationFactor/HINGE_JOINT_LIMIT_RELAXATION

I did not yet implement soft limits for hinges for Jolt, but it is trivial to do so. It is almost the same code as ```SliderConstraintSettings::mFrequency/mDamping``` when the mode is set to ```StiffnessAndDamping```. I'll put that on my list as it is a useful feature.

Continuing to the next constraint in the next post...

**Comment by jrouwe** [comment]
**PinJoint3D**

PIN_JOINT_BIAS, PIN_JOINT_DAMPING and PIN_JOINT_IMPULSE_CLAMP

These are the stiffness, damping and impulse limits for the constraint. This effectively turns the point constraint in a spring in 3 axis. In Jolt the PointConstraint is always a hard constraint. This makes it cheap and adding softness will make it a bit more expensive. Not sure what to do here, I would personally use a DistanceConstraint for the cases where I want a spring (a 1 axis spring) which does support stiffness and damping but not the impulse limits (not hard to implement, but I never needed them).

**Comment by jrouwe** [comment]
**SliderJoint3D**

When ```SliderConstraintSettings::mSpringMode = ESpringMode::StiffnessAndDamping``` I think you can say :
SliderConstraintSettings::mFrequency = PARAM_LINEAR_LIMIT_SOFTNESS * PARAM_LINEAR_LIMIT_RESTITUTION
SliderConstraintSettings::mDamping = PARAM_LINEAR_LIMIT_SOFTNESS * PARAM_LINEAR_LIMIT_DAMPING

When there is anything in SLIDER_JOINT_LINEAR_MOTION_* I think you can set the motor to EMotorState::Position and then calculate it in the same way as above but then using SLIDER_JOINT_LINEAR_MOTION_*.

SLIDER_JOINT_LINEAR_ORTHOGONAL_* is a spring in the orthogonal direction to the slider axis. This is not supported by Jolt and if it has been configured you'd need to switch to a SixDOFConstraint. The values work the same again.

SLIDER_JOINT_ANGULAR_* allows you to have the slider joint rotating. Again this is what the SixDOFConstraint is for. I don't think Jolt should support this for the SliderConstraint as it is meant to be a cheap constraint with limited features.

**Comment by jrouwe** [comment]
**ConeTwistJoint3D**

Restitution and damping seems to be interpreted as usual here (stiffness and damping) but this time the [softness is treated differently](https://github.com/godotengine/godot/blob/543750a1b3f5696f9ba8e91cb49dc7db05d2ae62/servers/physics_3d/joints/godot_cone_twist_joint_3d.cpp#L207). It appears that it affects when the limits are enforced rather than how much they are enforced. I don't understand why it is different from the slider joint. In any case I did not implement soft limits for the SwingTwistConstraint in Jolt. This should be simple just like with the hinge constraint but I have to think if it is worth it to support this (or if you should use a SixDOFConstraint instead, which is not much more expensive).

**Comment by jrouwe** [comment]
**Generic6DOFJoint3D**

This is the big one. 

G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS, G6DOF_JOINT_LINEAR_RESTITUTION, G6DOF_JOINT_LINEAR_DAMPING - Jolt stiffness = softness * restitution and Jolt damping = softness * damping like before (when the mode is StiffnessAndDamping). However these make the limits soft which Jolt doesn't support. I will add that support just like on the hinge.

G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS, G6DOF_JOINT_ANGULAR_RESTITUTION, G6DOF_JOINT_ANGULAR_DAMPING - Strangely enough this appears to be working different from the other constraints again. I have no idea what G6DOF_JOINT_ANGULAR_RESTITUTION does, but it appears that in this case G6DOF_JOINT_ANGULAR_ERP is actually the restitution. Again, Jolt doesn't support soft limits so none of this can be used at the moment. I will add this.

So the funny thing is that I now made it possible to support G6DOF_JOINT_LINEAR_SPRING_* and G6DOF_JOINT_ANGULAR_SPRING_*, by making the motors of the SixDOFConstraint support stiffness/damping, but the godot implementations of these are [empty](https://github.com/godotengine/godot/blob/543750a1b3f5696f9ba8e91cb49dc7db05d2ae62/servers/physics_3d/joints/godot_generic_6dof_joint_3d.cpp#L511)...

**Comment by jrouwe** [comment]
Summarizing:

I'm not really sure what you tested because the changes I made seem to be of very limited use at this moment. I will finish the change though because I think it is a good one and needed to support the other features that I need to add:

* Supporting soft limits on hinges
* Supporting soft limits on SixDOF constraints
* (perhaps) Supporting soft limits on SwingTwist constraints

Now that I have looked at all joints I think you could:

* For the hinge, you probably want to do softness * relaxation and softness * damping just like the other joints (I'll check if a bug has been reported for this already)
* Switch to a SixDOFConstraint when a PinJoint3D has a bias
* (perhaps) Switch to a SixDOFConstraint when a ConeTwistJoint3D has a restitution

**Comment by jrouwe** [comment]
I opened up a new issue for godot here: https://github.com/godotengine/godot/issues/77851

**Comment by mihe** [comment]
Thank you for the incredibly detailed response. I certainly did not expect that.

## HingeJoint3D

> HINGE_JOINT_BIAS - You can simply ignore this one. [...]

Good to know! Maybe I should change the warning message to something more informative based on the information you provided.

> HINGE_JOINT_LIMIT_SOFTNESS - It appears that this value is not used for anything at all in Godot!

> I opened up a new issue for godot here: godotengine/godot#77851

As I understand it all of the constraint code in Godot Physics originates from Bullet, and when looking at the code in Bullet it appears that this holds true there as well, [from what I can tell](https://github.com/bulletphysics/bullet3/blob/39b8de74df93721add193e5b3d9ebee579faebf8/src/BulletDynamics/ConstraintSolver/btHingeConstraint.h). A bit strange to copy that part verbatim, but I guess they weren't aware that this was unused when first exposing that parameter in Godot 3, and for some reason decided to carry it over into Godot 4 and Godot Physics.

> HINGE_JOINT_LIMIT_BIAS, HINGE_JOINT_LIMIT_RELAXATION - [...] I did not yet implement soft limits for hinges for Jolt, [...] I'll put that on my list as it is a useful feature.

Glad to hear it!

> For the hinge, you probably want to do softness * relaxation and softness * damping just like the other joints (I'll check if a bug has been reported for this already)

Gotcha, I'll give this a try.

## PinJoint3D

> In Jolt the PointConstraint is always a hard constraint. This makes it cheap and adding softness will make it a bit more expensive. Not sure what to do here

> Switch to a SixDOFConstraint when a PinJoint3D has a bias

I touch on this more in the `SliderJoint3D` stuff below, but I do feel like Jolt should keep having the simpler constraints be simple/cheap and let 6DOF do any heavy lifting. That seems very reasonable to me.

## SliderJoint3D

> I think you can say :
SliderConstraintSettings::mFrequency = PARAM_LINEAR_LIMIT_SOFTNESS * PARAM_LINEAR_LIMIT_RESTITUTION
SliderConstraintSettings::mDamping = PARAM_LINEAR_LIMIT_SOFTNESS * PARAM_LINEAR_LIMIT_DAMPING

Awesome, I'll give this a try as well.

> SLIDER_JOINT_ANGULAR_* allows you to have the slider joint rotating. Again this is what the SixDOFConstraint is for. I don't think Jolt should support this for the SliderConstraint as it is meant to be a cheap constraint with limited features.

I agree. This is something I struggled with when implementing things like `SliderJoint3D`. Obviously you could implement pretty much every single constraint with a 6DOF constraint, but then there wouldn't be much point to having them, besides perhaps ease-of-use. I considered switching the backing Jolt constraint as-needed, but deemed the complexity (and potential need for documenting this) to not be worth it at the time, and settled instead for just suggesting `Generic6DOFJoint` in the warning message. Maybe I should take another look at this though.

## ConeTwistJoint3D

> I did not implement soft limits for the SwingTwistConstraint in Jolt. This should be simple just like with the hinge constraint but I have to think if it is worth it to support this (or if you should use a SixDOFConstraint instead, which is not much more expensive).

> (perhaps) Switch to a SixDOFConstraint when a ConeTwistJoint3D has a restitution

My comments under `PinJoint3D` and `SliderJoint3D` apply here as well I guess.

## Generic6DOFJoint3D

> G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS, G6DOF_JOINT_LINEAR_RESTITUTION, G6DOF_JOINT_LINEAR_DAMPING [...] I will add that support just like on the hinge.

> G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS, G6DOF_JOINT_ANGULAR_RESTITUTION, G6DOF_JOINT_ANGULAR_DAMPING [...] I will add this.

Great!

> I now made it possible to support G6DOF_JOINT_LINEAR_SPRING_* and G6DOF_JOINT_ANGULAR_SPRING_* [...] but the godot implementations of these are empty...

Yes, I also stumbled upon the empty implementations of the spring parameters in Godot Physics as I was testing this yesterday. I'll admit I had completely forgotten that this part wasn't actually implemented in Godot Physics yet, although there seems to have been some movement there recently. The constraints in Godot Physics in general are in a fairly frustrating state though, where no matter what values you tweak the constraint end up exploding at some point, making it difficult for a layman like myself to A/B test stuff, which has led me to mostly compare against the Bullet implementation in Godot 3 instead, where all of this originated from.

There is another 6DOF spring parameter in Godot/Bullet that I'm curious about though, which is the `G6DOF_JOINT_*_SPRING_EQUILIBRIUM_POINT` parameter. I haven't found any documentation about this in Godot 3, Godot 4 or Bullet, so I'm not quite sure what it's meant to do. When looking at [the code in Bullet](https://github.com/bulletphysics/bullet3/blob/39b8de74df93721add193e5b3d9ebee579faebf8/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp#L118) it seems to be some kind of offset, I guess?

## Summary

> I'm not really sure what you tested because the changes I made seem to be of very limited use at this moment.

Practically speaking, what I did was simply to pass `G6DOF_JOINT_*_SPRING_STIFFNESS` and `G6DOF_JOINT_*_SPRING_DAMPING` on to `mFrequency` and `mDamping` respectively, and enable `EMotorState::Position` along with `ESpringMode::StiffnessAndDamping` if springs were enabled, which seemed to net me similar results in my (somewhat crude) tests to what I was seeing with Bullet in Godot 3, although I had to use slightly different values.

I didn't mean to imply that this somehow had finished off the 6DOF constraint though, if that was how it came off, but I still think "only" adding support for stiffness/damping on the 6DOF joint carries a lot of disproportionate weight, since it opens up for things like suspension, trampolines and whatever else people use springs for.

**Comment by jrouwe** [comment]
>>G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS, G6DOF_JOINT_LINEAR_RESTITUTION, G6DOF_JOINT_LINEAR_DAMPING - Jolt stiffness = softness * restitution and Jolt damping = softness * damping like before (when the mode is StiffnessAndDamping). However these make the limits soft which Jolt doesn't support. I will add that support just like on the hinge.

> Just so I'm understanding this correctly. Are you saying I should set mFrequency/mDamping (with the StiffnessAndDamping mode) to the value of those calculations, like with the other joints? 

When I add soft limits for the SixDOFConstraint then you can set the frequency/damping of the soft limits to these values. Right now you cannot do anything with them.

> If so, how does this work with G6DOF_JOINT_LINEAR_SPRING_STIFFNESS and G6DOF_JOINT_LINEAR_SPRING_DAMPING?

These values go into the motor settings for the linear axis and then you need to set the motor to position. Just like you mention later on in **Summary**.

> G6DOF_JOINT_*_SPRING_EQUILIBRIUM_POINT

This one goes into SetTargetPositionCS for the linear components and to SetTargetOrientationCS for the angular components (and I think you need to interpret them as Euler angles and convert them to a quaternion using Quat::sEulerAngles (and hope the intended rotation order is XYZ). It is basically the XYZ position and rotation that you're driving the constraint to.

> The constraints in Godot Physics in general are in a fairly frustrating state though, where no matter what values you tweak the constraint end up exploding at some point

This is basically why I chose the frequency and damping values. Stiffness and damping depend on mass (and at which point on your shape the spring connects) so are very unintuitive. With frequency and damping you can pick a value that works well for everything.

B.t.w. If, after I implement things on my side, you think you've implemented the parameters then feel free to send me a review (even if you haven't tested things yet). The number of properties is quite large and it's hard to explain exactly what goes where here.

**Comment by mihe** [comment]
> When I add soft limits for the SixDOFConstraint then you can set the frequency/damping of the soft limits to these values. Right now you cannot do anything with them.

Ah, gotcha, I misunderstood.

> This one goes into SetTargetPositionCS for the linear components and to SetTargetOrientationCS for the angular components (and I think you need to interpret them as Euler angles and convert them to a quaternion using Quat::sEulerAngles (and hope the intended rotation order is XYZ). It is basically the XYZ position and rotation that you're driving the constraint to.

I was sitting here thinking what a shame I couldn't do something like `SetTargetOrientationCS` after seeing it in your constraint vehicle example. I need to try this one out then.

> B.t.w. If, after I implement things on my side, you think you've implemented the parameters then feel free to send me a review (even if you haven't tested things yet). The number of properties is quite large and it's hard to explain exactly what goes where here.

That would be great! This is definitely a lot stuff to juggle, and just getting the constraints to the barebones state they're in currently was a surprising amount of work for me, so I'm sure these new parameters will prove to be a challenge as well.

**Comment by jrouwe** [comment]
I refactored a bit of code because a lot of code was being duplicated but now (on the branch) the hinge supports soft limits, so I think you should have everything to implement the HingeJoint3D. 

Next up is soft limits for the SixDOFConstraint.

**Comment by jrouwe** [comment]
Soft limits for 6DOF position limits are implemented, the orientation is a bit more work and I'm not sure if I'm going to do that at all, let's see if someone needs them.

Everything has been merged to master.

Closing this issue for now.
