### ISSUE TITLE
Collision Filtering - source and target bitmasks

### ISSUE THREAD

**Issue by DevLewa** [jrouwe/JoltPhysics#744]
I have a question with regards to collision filtering in Jolt.
In Jolt (from what i've been able to research going through the code) the filtering is done by using the 
ObjectVsBroadPhaseLayerFilter and ObjectLayerPairFilter callbacks. Both of them provide the

`virtual bool ShouldCollide(JPH::ObjectLayer inLayer1, JPH::BroadPhaseLayer inLayer2) const override`

function whereas each Object is assigned to a specific layer.

This means that for example if we define an ObjectLayer "Vehicle" and another Layer "Wall" and want both of them to collide with each other we can implement this as:

```
virtual bool ShouldCollide(JPH::ObjectLayer inObject1, JPH::ObjectLayer inObject2) const override
{
    if(inObject1 == Layers::Car)
    {
        return inObject2 == Layers::Wall;
    }
    return false;
}
```

My question is if it is possible to implement a similar system like in PhysX and in Bullet where a Rigidbody/Shape has 2 Layers defined. (A source layer and a target layer.)

in PhysX for example the Callback is implemented like this:
```
static bool preFilterCheck(const physx::PxFilterData& filterData, const physx::PxShape* shape, const physx::PxRigidActor* actor, physx::PxHitFlags& queryFlags)
{
	if ((filterData.word0 & shape->getQueryFilterData().word1) && (shape->getQueryFilterData().word0 & filterData.word1))
	{
		return true;
	}
	return false;
}

```
So in the above example in order for the two shapes/rigidbodies to collide the source layer of object A needs to be present in the target layer of B and vice versa.
For example as an illustration (pseudocode)

```
Object car; 
car.srcMask = Layer::Car;
car.trgMask = Layer::Wall;

Object wall;
wall.srcMask = Layer::Wall;
wall.trgMask = Layer::Car;

//Both objects can collide due to the bitmask combination
```

The advantage of this is that you can be a lot more flexible and have more direct control as to which objects can collide with each other.
If you for example want to create a Wall which doesn't collide with a car, simply remove the "Car" layer from the target mask.
From what i've seen you can only set a single Layer (either as a 16 bit or 32 bit integer) in the BodyCreationSettings for the object.

Is this feature already present in Jolt? (Or can be this easily added without heavy source code modification? PhysX had a reserved void*  field for shapes in order to store custom filtering data if the existing bitfields were not enough.)
I could of course try tro cram the source/target bitmask into the 32 bit integer of the ObjectLayer (16 bits for each mask) and modify the filtering callbacks to perform this check (splitting the integer into those two masks there) as a fallback for now but this is more of a workaround which doesn't allow me to extend the size of the bitmask above 16 bits in the future.

**Comment by mihe** [comment]
> I could of course try tro cram the source/target bitmask into the 32 bit integer of the ObjectLayer (16 bits for each mask) and modify the filtering callbacks to perform this check (splitting the integer into those two masks there) as a fallback for now but this is more of a workaround which doesn't allow me to extend the size of the bitmask above 16 bits in the future.

There might be a more clever way to go about this, but what I did (and I believe other Jolt users as well) was to simply store a lookup somewhere, which in my case was the `ObjectLayerPairFilter` class, that maps the object layer to whatever format I needed it to be, which in my case also happened to be two 32-bit integers. So when an object is created I request the object layer for source mask X and target mask Y, and it either gives me the existing object layer for that pair or generates a new one. Then once `ShouldCollide` is called I just do the reverse lookup on both object layers and check the masks.

In my case I decided to also encode the broadphase layer into 3 of the object layer bits (leaving me with 13 bits or 8192 possible combinations of layers and masks when using a 16-bit object layer) so that I could quickly derive the broadphase layer in `ObjectVsBroadPhaseLayerFilter`, but that might frankly have been a case of premature optimization. A simple lookup might have been just fine there as well. I can't say I've really seen any of the filtering show up in any of my profiling.

[Here](https://github.com/godot-jolt/godot-jolt/blob/master/src/spaces/jolt_layer_mapper.cpp) is the entirety of that code, if it's of any help.

**Comment by DevLewa** [comment]
Using a lookup table is certainly a solution. (Why haven't i thought of that.)
What i might end up doing is to generate a unique ID per rigidbody (starting from 0 and incrementally going up), store this ID in the ObjectLayer field and use this to index into an array which stores all nessecary collisionfiltering information per object.

Something along the lines of:
```
struct FilteringInfo
{
    std::uint32_t sourceMask;
    std::uint32_t targetMask;
};

std::vector<FilteringInfo> lookupTable;

std::uint32_t rigidBodyId = 0;

std::uint32_t createUniqueID()
{
    return rigidBodyId++;
}

//creating rigidbody
JPH::BodyCreationSettings bodySettings(shape, ... ,createUniqueID()); // instead of specifying layer we create a new Id for the rigidbody

//callback
virtual bool ShouldCollide(JPH::ObjectLayer inObject1, JPH::ObjectLayer inObject2) const override
{
    const auto& lookupA = lookupTable[static_cast<std::uint32_t>(inObject1)];
    const auto& lookupB = lookupTable[static_cast<std::uint32_t>(inObject2)];

    if ((lookupA.sourceMask & lookupB.targetMask) && (lookupB.sourceMask & lookupA .targetMask))
    {
         return true;
    }
    return false;
}
```

Thank you for the fast response. Should be solved.
