### ISSUE TITLE
Building with clang using ninja on windows

### ISSUE THREAD

**Issue by Hatrickek** [jrouwe/JoltPhysics#766]
Currently Jolt doesn't build with clang on Windows because of this line: <https://github.com/jrouwe/JoltPhysics/blob/master/Build/CMakeLists.txt#L82>

Giving this error:
```
CLANG_~1: error: no such file or directory: '/Zc:__cplusplus'
CLANG_~1: error: no such file or directory: '/Gm-'
CLANG_~1: error: no such file or directory: '/MP'
CLANG_~1: error: no such file or directory: '/nologo'
CLANG_~1: error: no such file or directory: '/diagnostics:classic'
CLANG_~1: error: no such file or directory: '/FC'
CLANG_~1: error: no such file or directory: '/fp:except-'
CLANG_~1: error: no such file or directory: '/Zc:inline'
CLANG_~1: error: no such file or directory: '/Zi'
CLANG_~1: error: no such file or directory: '/GR-'
CLANG_~1: error: no such file or directory: '/showFilenames'
CLANG_~1: error: no such file or directory: '/GS-'
CLANG_~1: error: no such file or directory: '/Gy'
CLANG_~1: error: no such file or directory: '/O2'
CLANG_~1: error: no such file or directory: '/Oi'
CLANG_~1: error: no such file or directory: '/Ot'
```

I could simply fix it by adding ```AND NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang"``` to the top if check in my fork and it built and run successfully.
https://github.com/Hatrickek/JoltPhysics/blob/master/Build/CMakeLists.txt#L69

**Comment by cranflavin** [comment]
I hit the same issue as @Hatrickek (apparently 7 hours after). The workaround is good to get buildling/running, although it may be that skipping that `if` block means some of the build configurations won't be set up right. I have been using cmake/ninja/clang for builds.

**Comment by mihe** [comment]
https://github.com/jrouwe/JoltPhysics/blob/6535d6ca60a47bed90153730b3fc3a409d48e274/Build/CMakeLists.txt#L69

I would probably advise just replacing that whole thing with `if (MSVC)`, which will be truthy whenever the compiler defines `_MSC_VER`, which would cover Microsoft's own `cl` as well as `clang-cl`, but none of the compilers adhering to the GCC-like interface, like MinGW-based compilers or (in this case) native `clang`.

https://github.com/jrouwe/JoltPhysics/blob/6535d6ca60a47bed90153730b3fc3a409d48e274/Build/CMakeLists.txt#L131

Then this could probably just be an `else()`, since any other supported compiler is likely to emulate the GCC-like interface anyway, including native `clang` on Windows.

**Comment by jrouwe** [comment]
I like @mihe's solution better. I've created a #767 and it looks like it passes all builds. Can you let me know if this works for ninja too? (I don't use it)

**Comment by cranflavin** [comment]
I can confirm that @mihe's solution works for my cmake/clang/ninja setup.

**Comment by Hatrickek** [comment]
It indeed works thanks 🙂
