### ISSUE TITLE
BodyInterface is missing functions to apply forces

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#85]
There are functions for AddImpulse and AddAngularImpulse, but nothing for forces. I know it would be easy to add those, but I am hesitant to contribute actual code changes myself, since I work closely with the Havok team (MS employee) and some might see that as crossing a line.

**Comment by jrouwe** [comment]
Very understandable, the same policy goes for us (I got an exception for Jolt). I've added the interface in #87 but I want to point out that the reason these functions didn't exist is that you should try to avoid calling many functions on the BodyInterface. If you use the locking variant you have the overhead of a mutex lock for every call to BodyInterface, for the non-locking variant you may have a cache miss because the BodyID needs to be converted to a Body. If you need to do multiple things with the same body, I would take the lock in client code and apply all changes under 1 lock (e.g. it's very likely that you will need the position of the body to calculate the force so BodyInterface::GetPosition followed by BodyInterface::AddForce will have extra overhead).
