### ISSUE TITLE
Character Controller ground detection problems

### ISSUE THREAD

**Issue by jankrassnigg** [jrouwe/JoltPhysics#88]
The way the character controller checks for the ground state has a few problems.

It simply makes an overlap check with the character shape at the current location to determine which bodies it touches. Unfortunately, this is very unreliable. In many cases there will be no overlap at all, simply because after the simulation the CC is standing ON the ground, but not PENETRATING the ground and thus the check may or may not return the ground body, depending on floating point accuracy I'd guess.

Simply debug drawing the ground position of the CC and the ground state shows that it flickers between different states. It becomes very apparent when you want to apply the ground velocity (moving platforms), which randomly slide away beneath the CC.

One way I have attempted to fix this, is to move the ground check artificially 1cm downwards. This fixes the ground detection BENEATH the CC.
However, the 'sliding' state is equally affected by this. Once you jump into a wall, the overlap check may or may not return the wall object and thus vary between 'sliding' and 'in air'. To prevent the player to be able to pin the CC to a wall by walking/flying into it, I want to clamp the input velocity against the touched surface. So I need to reliably know when the CC touches a wall. Here I can't use the 'move a tiny bit downwards' tricky though. Instead, the CC shape would need to be expanded slightly. Since the user provided CC shape is used for the overlap check, I currently don't see how this could be accomplished inside Jolt.

At the moment I think my best bet would be to copy&paste the Jolt CC ground detection code into my code, and adjust it with my own (known) expanded capsule shape. Not a horrible solution actually, but maybe you have an idea how to make this more usable for everyone.

**Comment by jrouwe** [comment]
I see I made a mistake in Character::PostSimulation, inMaxSeparationDistance was not used, which indeed causes this flickering behavior (as the capsule is not padded because of that). I submitted a fix.

For player movement I would recommend:
- Use regular CollideShape / CastShape calls to determine where the player should go (we use CollideShape with a mMaxSeparationDistance that is about the size you can step in 1 frame, treat all contact points and their normals as planes and slide the capsule along those planes, finally we validate that we didn't go through the world by doing a CastShape)
- Use a JPH::Character to give your virtual character presence in the world (we don't give it gravity and just move it along using SetLinearVelocity in order to push other things around in the world)

The advantage of this is that you can calculate an updated position for your player during the game code update (and don't need to wait until the physics update) and that you have far greater control over how your character moves.

**Comment by jankrassnigg** [comment]
Interesting, I already assumed I should do a lot on my own from the rather sparse feature set of the CC.

I'll do some experiments soon (hopefully).

Btw. the maxSeperationDistance fix made it work for the ground contact, however, it doesn't seem to have an effect on walls. E.g. jumping into a wall (such that there is no ground contact), even with a relatively large separation distance (0.1 or so) doesn't make it detect the wall (only sometimes due to imprecision). Is this supposed to work in all directions?

**Comment by jrouwe** [comment]
Yes, it is an extra convex radius, so it should detect it on all sides. There is however a condition in Character::PostSimulation::MyCollector that discards any normals where dot(normal, gravity) >= 0, and my guess is that your wall normal is discarded because of it (mBestDot is initialized to 0). We could make that configurable, but the idea was to only return points that you could stand on, so a vertical wall is ignored. 

I'm considering to make a 'VirtualCharacter' class that implements the rules that I outlined in my previous post to make it easier to create your own in game character.

**Comment by jrouwe** [comment]
I submitted a fix in 452d6fe8c8850bb7984bcf2cab48cf62d3b66201. I think it's ok to also detect ground normals when the normal is horiziontal or pointing down. GetGroundState will then return Sliding so it would be up to the application to decide what to do with it.

**Comment by jankrassnigg** [comment]
Oh, I thought it was already doing that, but I must have missed that it was ignoring normals above 90 degrees. And at exactly 90 degrees it ended up being a bit random.

**Comment by jankrassnigg** [comment]
> treat all contact points and their normals as planes and slide the capsule along those planes

I am doing this myself now, however, even though it works pretty well with most geometry, there are several cases where my code fails pretty badly.

The most simple case is, if you have two equally sized (static) boxes next to each other, that touch with one face. To the player it looks like a smooth wall. However, when you slide along that wall, you'll come to the seam between the boxes and here you'll get several contact points whose normals contradict each other.

My sliding algorithm takes the intended movement direction and attempts to clamp it along these planes, however, here the planes would push the vector back and forth between different directions, and after a couple of attempts I have to give up and make the character just stop.

Do you have a good approach to somehow filter the contact points to know which ones to use?

**Comment by jrouwe** [comment]
Take a look at CollideSettingsBase::mActiveEdgeMovementDirection, this should solve the issue for triangle meshes (this basically tells the system to pick the normal that doesn't oppose the movement direction). For boxes however that won't work (cause it's not implemented there). I'm currently working on the virtual character code and I'll see if I can replicate the problem you're describing.

**Comment by jankrassnigg** [comment]
Awesome, I'll give it a try as soon as I can, though it may be a couple of days before I get the time.

**Comment by jrouwe** [comment]
I merged the branch with master. There's still some loose ends (if you're supported by more than 2 steep slopes you get jitter), but in general I think it is a good first version.

**Comment by jankrassnigg** [comment]
I've finally gotten the time to give the virtual character a try. It works really, really nicely. Much more like the PhysX character controller that I had used before (which is also a non-dynamic body) and gives you much more control, I really prefer this approach.

I still implement a couple of things myself on top of this, most notably I have a step height that the character will step up/down within one frame, such that it can easily climb stairs and also hugs the ground when going down certain slopes. For that to work I keep the character always floating above ground for this allowed step height, make a downward shape cast and detect the ground state myself (and apply gravity as needed), so I'm not using all of the built-in features.

I made a quick test for being pushed by kinematic objects and that's when I observed some rather weird behavior. I haven't had the time yet to fully investigate, but I can't explain it with my own code. Basically, when the CC gets into contact with a kinematic object, it sometimes starts acting erratic, being pushed by the object even when it is far away (sometimes the CC is literally teleported away 10 meters for no apparent reason).

Here is a video:
https://1drv.ms/v/s!Ajrhg3sdAbZvkOVpnxOSiCWhIaOJgw?e=motSqZ

Once it is in that state, it continues being erratic, until I walk into some other wall in a particular way.

I'm wondering, whether the virtual character internally stores information about previously touched objects and gets confused when the CC is being pushed from the outside? Touching another wall seems to clear that incorrect information again.

Note that a) my up axis is +Z and b) my CC is always floating above ground, so even though the CC appears to be touching the ground, in fact it isn't and thus only walking into a wall results in a new contact.

I'll investigate this further soon, but thought you might have an idea whether this could be an issue inside Jolt.

**Comment by jankrassnigg** [comment]
Oh and one more thing: CharacterVirtual::SetShape has this feature to check whether the new shape would overlap geometry. It would be useful, if this logic would be more generally available. E.g. I want to check whether I can safely teleport somewhere. I can achieve this manually, but it would be mostly doing the same as what's already there.

So would be cool, if the character had a CheckOverlap(position, optional new shape) function, where I can either pass in a new shape, or nullptr and then it just takes the current shape to check for overlaps at that location.

**Comment by jrouwe** [comment]
Can you try replacing your cylinder shape with a capsule shape? My guess is that the issue happens because the contact point for a cylinder vs plane is not well defined (cylinders are more expensive in general than capsules). There should not be any state kept from step to step (mActiveContacts is overwritten every time).

I'll make a CheckOverlap function, and I was planning to make something for stair walking too. I'm curious how your technique works, we do a sweep up, forward and then down.

**Comment by jankrassnigg** [comment]
I've tried a capsule shape, but that didn't make a difference. The reason I used a cylinder was that I wanted to have precise control over the allowed step height. With a cylinder, if I have it hover 20cm above ground, an obstacle that's 21cm high will be a blocker, whereas with a capsule there is always some wiggle room that even depends on the characters width.

However, I think I've found the issue. The way we usually step the physics simulation is a bit complicated to accomodate for variable frame rates and I guess because of the 250+ FPS that I had, some frames skipped a physics update and somehow the effect of that could be catastrophic. If I set it to one update every frame, no matter what, the character follows the ground as desired.

The whole stepping thing is something I need to look into more closely at some point anyway. Though I'm wondering, if I use sub-steps, do I need to hook into those and update the characters during each sub-step, or only once after the entire update is through?

Regarding stair stepping:
I guess your solution is better, and it's what I would have preferred, though since I first attempted to use the non-virtual Character, where arbitrarily moving it around within one frame wasn't an option, here is my current solution:

* I let the VirtualCharacter hover over the ground, so that when moving forwards it can always get over those small obstacles
* At the position where I want to go, I make a shapecast with a cylinder downwards (within the step up/down range), look at all the contacts and if any of them is flat enough I take the closest flat-enough contact as the 'ground contact'. If all contacts are from too steep surfaces, I take the flatest one as the ground contact.
* I then take my direction vector where I want to go and adjust the up vector so that the character either steps up or down accordingly, though I (currently) only take 25% of that up/down value, so that it doesn't fully snap in one frame, but has at least a very slight smoothing over time. Not sure whether this is actually a good thing.

Honestly, the more stuff that's already handled by Jolt, the better for me (and others). The only problem is, that such automatisms have to be controllable. For example once I'm jumping I MAY want to allow that the character still steps UP a bit when it hits a ledge, but DON'T want it to step DOWN when it gets close to the ground, but only want to reenable that once it touched the ground. Or I may want to disable stepping completely while jumping/falling. I also may want to change the step height when I change the stance. So this should be fully adjustable every frame.

**Comment by jankrassnigg** [comment]
I've finally managed to get to the bottom of the weird character behavior.

We have three modes for physics updates: variable time-step, fixed time-step and semi-fixed time-step. The latter two will try to only simulate with a fixed time-step and if necessary will skip simulation and accumulate more time.

The problem is, that even if a simulation update got skipped, I still applied the kinematic body linear velocity. This worked in PhysX, because there you just give it a target orientation and that's it, the rest is done during the simulation step. In Jolt you have to set a velocity AND A TIMESTEP. First of all, I gave it the wrong time delta (not the accumulated one). Second, if simulation was skipped multiple frames in a row, updating the kinematic bodies multiple times without a simulation step in between would flat out crash.

I don't know how, but in BodyManager::ValidateActiveBodyBounds the assert (cached == calculated) would produce an NaN in one of the values in my test, and even though the result was identical, NaN compares of course always fail. After that it would also assert in a couple of other places.

After fixing all that, the character is properly pushed by the kinematic body.

**Comment by jrouwe** [comment]
> The whole stepping thing is something I need to look into more closely at some point anyway. Though I'm wondering, if I use sub-steps, do I need to hook into those and update the characters during each sub-step, or only once after the entire update is through?

I'm assuming we're still talking about CharacterVirtual. If that's the case: CharacterVirtual is in no way related to your physics simulation. It only does something when you call Update() and then it steps based on inDeltaTime and the current linear velocity of the character. The only time it interacts with the simulation is if you start pushing dynamic objects. It does this through impulses, but if you run your character at a higher frequency than your physics simulation, the character may apply the wrong (too large) impulse to a dynamic body simply because that body didn't move (the dynamic body only moves in the physics step, the character when you call Update).

> For example once I'm jumping I MAY want to allow that the character still steps UP a bit when it hits a ledge, but DON'T want it to step DOWN when it gets close to the ground, but only want to reenable that once it touched the ground.

The way I envision this working is that there will be a WalkStairs function where you specify an Up and Forward vector. You'd call that WalkStairs function if you detect that you hit a vertical blocker in the Update function. It would first perform a sweep Up (define UpActual is how far we got until we collided), then a sweep Forward and finally a sweep -UpActual. If the character ends up not colliding with anything or colliding with something too steep then the WalkStairs would fail. Otherwise it would reposition the character to the new location. It's up to you when you call the WalkStairs function and you'd obviously not do that when jumping.

> I don't know how, but in BodyManager::ValidateActiveBodyBounds the assert (cached == calculated) would produce an NaN in one of the values in my test, and even though the result was identical, NaN compares of course always fail. After that it would also assert in a couple of other places.

I'm currently chasing an issue where NaN's enter the simulation somehow, so if you have any idea what happened then I'm very interested. If the bounding boxes are NaNs then most likely the body's position/rotation is NaN too and that's obviously not supposed to happen.

**Comment by jankrassnigg** [comment]
> I'm currently chasing an issue where NaN's enter the simulation somehow, so if you have any idea what happened then I'm very interested.

My most basic test was this: A single kinematic box (unit cube). Run the simulation at 60 Hz but update the kinematic box 3 or more times in between steps. I had the box moving back and forth along the X axis. I guess I called "MoveKinematic" with a 1/250 time step.

After 2-3 seconds the simulation would assert.

**Comment by jankrassnigg** [comment]
I'll close this ticket. I have created new tickets for related things discussed here.
