### ISSUE TITLE
DirectX Error

### ISSUE THREAD

**Issue by cuppajoeman** [jrouwe/JoltPhysics#988]
Hi there,

I just got windows to test out the Jolt Samples, I'm compiling with msys2 using the urct profile. I followed the steps in the Build directory and everything compiled correctly and all tests pass. 

When I try to run `Samples.exe` I get the following error: 

![image](https://github.com/jrouwe/JoltPhysics/assets/19198104/d9b7bc4f-e443-427a-90cb-ba6cedb5c41a)

I tried looking up this error but I haven't been able to find the cause, the computer is a lenovo thinkpad T470: 
![image](https://github.com/jrouwe/JoltPhysics/assets/19198104/71eb034d-ee22-424a-accc-d3baa9591bf4)
![image](https://github.com/jrouwe/JoltPhysics/assets/19198104/d24f582b-a057-4cd0-b7f7-ba0c326d3ed5)

**Comment by jrouwe** [comment]
The error is:

```
DXGI_ERROR_DEVICE_REMOVED
0x887A0005
```

which is a very generic error that doesn't say much.

First thing to check is if your graphics drivers are up to date.

Next thing would be to run Samples in Debug mode and look at the debugger output (usually it traces a meaningful message because the DirectX debug layer is active in debug mode). Easiest way to get to the debugger output is to compile and run everything using Visual Studio 2022 (free to download). In MSYS2 it is probably also possible but you'll need an external tool like [DebugView++](https://github.com/CobaltFusion/DebugViewPP) to view the debug output.

Perhaps you can also break the application when the error message triggers to get the callstack (and line number) where the problem happens.

**Comment by cuppajoeman** [comment]
Ok, so I was able to get some more info through the CLion IDE which gives me some easy debugging utilities. 

![image](https://github.com/jrouwe/JoltPhysics/assets/19198104/084d4a1e-2926-4924-83f0-3a48a80585b1)

```gdb

```

**Comment by jrouwe** [comment]
I don't know why that's not allowed on your machine, on my machine that's the only value that is allowed.

You can work around this by commenting out the shadow rendering code:

https://github.com/jrouwe/JoltPhysics/tree/test/no_shadows

**Comment by cuppajoeman** [comment]
Hey @jrouwe I just tested on the `test/no-shadow` branch, on this branch when I compile and run the `Samples` target I get everything running just without shadows.

**Comment by jrouwe** [comment]
Adding the patch for future reference before deleting the branch:

[no_shadows.patch](https://github.com/jrouwe/JoltPhysics/files/14671904/no_shadows.patch)
